dev/18.x Release linking error fixes
lanl/kitsune pull request #49
Opened 2024-08-27 16:19 UTC by stelleg

clang/lib/Frontend has a call to a Tapir << operator, which means it has to be linked against TapirOpts.

There's  unguarded checks to Value::dump in HipABI, which is disabled for release builds, so I've replaced them with LLVM_DEBUG calls. Note this means you don't have that output before assertion failure for release builds. Other options if that's important.

2024-08-27 16:23 UTC, tarunprabhu commented
Ugh! Right. This actually needs a changes to a number of CMakeLists.txt files.. Joseph ran into this and has them fixed. I think it would be better to get all the changes from him. I'll work with him to get a PR in.

2024-08-28 23:57 UTC, tarunprabhu requested changes
Could you remove HipABI.cpp from this PR? It seems to be unrelated. It would be good to have a reasonable commit history on the main LANL repo. The history is pretty messed up at this point, but we can try not to mess it up too much. It would make merges easier.

2024-08-29 00:01 UTC, tarunprabhu commented
No one else is seeing your link error which is very strange. Still, the changes here (barring the ones in `HipABI.cpp`) should not cause any problems, so we should merge this.

2024-08-29 00:09 UTC, stelleg commented
`HipABI.cpp` is part of this because it's also causing linking failures, due to dump() not existing in Release mode. I can make a separate PR for that if you want.

2024-08-29 00:15 UTC, tarunprabhu approved these changes

2024-08-29 00:16 UTC, tarunprabhu commented
> `HipABI.cpp` is part of this because it's also causing linking failures, due to `dump()` not existing in Release mode. I can make a separate PR for that if you want.

No need to separate it if that is the case. Thanks for the clarification.

2024-08-29 00:22 UTC, stelleg commented
> No one else is seeing your link error which is very strange. Still, the changes here (barring the ones in `HipABI.cpp`) should not cause any problems, so we should merge this.

I think it's weird too, because everyone is using custom linking cmake configurations. I expect if anyone builds without any custom linking flags (i.e. the default) they will see similar issues.

2024-08-29 00:30 UTC, tarunprabhu commented
> I think it's weird too, because everyone is using custom linking cmake configurations. I expect if anyone builds without any custom linking flags (i.e. the default) they will see similar issues.

Perhaps. Anyway, I managed to turn off merge and rebase commits, so feel free to click on "squash and merge" whenever you like.

2024-08-29 13:59 UTC, pmccormick commented
LGTM.  Other changes inbound to address other build issues...

2024-08-29 16:21 UTC, merged